### ISSUE TITLE
Default behavior

### ISSUE THREAD

**Issue by callaertanthony** [viadee/external-task-retry-aspect#32]
Hi, first of all your work is fine ! Thanks for it !

My question is, why the default behavior is not : throwing the exception with no retry ?

Currently, the fact to just throw the exception from the external task required more code rather than the default retry behavior.
It should be great if by default the `RETRY_CONFIG` is not set, then a none retry (with 0) is set, rather than there is a 3 times default one.

What do you think about it ?

**Comment by rnschk** [comment]
Hi @callaertanthony, no problem for that. :) 

So, I just tried the retry aspect with the following configuration to confirm, that it will produce an incident immediately:
````yaml
de:
  viadee:
    bpm:
      camunda:
        external-task:
          retry-config:
            default-behavior: R0/PT1M
````

And regarding the 0-to-infinite-loop, I also tried a regular `JavaDelegate` with a Retry Time Cycle of `R0/PT1M`, and it produced an incident instantly, too. Though, there has been an issue concerning the error message when doing zero retries, but it was fixed in 7.14.2, see [CAM-12769](https://jira.camunda.com/browse/CAM-12769)

I'm not sure, if you still have an issue or any suggestion? If so, could you please elaborate a little more on that?
